name: Deploy Github Page
on: [push]
jobs:
    job0:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  target: wasm32-unknown-unknown
                  override: true

            - name: Setup cargo-make
              uses: davidB/rust-cargo-make@v1

            - name: Setup wasm-bindgen
              uses: jetli/wasm-bindgen-action@v0.1.0
              with:
                  version: "latest"

            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Run CI
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: "--release --target wasm32-unknown-unknown"

            - name: Run Wasm-bindgen
              run: wasm-bindgen target\wasm32-unknown-unknown\release\yezriel.wasm --out-dir wasm --no-modules --no-typescript

            - name: Create pages directory
              run: mkdir pages
            - name: Create pages/target directory
              run: mkdir pages/target

            - name: Copy index.html
              run: cp index.html pages/
            - name: Copy assets
              run: cp -r assets pages/
            - name: Copy yezriel.wasm
              run: cp release/yezriel.wasm pages/target/
            - name: Copy wasm.js
              run: cp release/yezriel.js pages/target/

            - name: Update Github Pages branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./pages
